/**
 * Templates Room — curated realistic short-form ideals
 * Categories: drama · action/thriller · product ads · intros · Nollywood · Asia
 */

export type TemplateRoomCategory =
  | "drama"
  | "action_thriller"
  | "product_ad"
  | "intro"
  | "nollywood"
  | "asia";

export type IdealRegion = "nigeria" | "asia" | "global";

export type IdealShot = {
  atSec: number;
  durationSec: number;
  framing: string;
  camera: string;
  note: string;
};

export type IdealTemplate = {
  id: string;
  category: TemplateRoomCategory;
  region: IdealRegion;
  name: string;
  tagline: string;
  durationSec: number;
  aspectRatio: "16:9" | "9:16" | "2.39:1" | "1:1";
  mood: string[];
  lut: string;
  stylePreset: string;
  idealUse: string;
  sampleScript: string;
  shots: IdealShot[];
  colorGrade: {
    contrast: number;
    saturation: number;
    temperature: number;
    shadows: string;
    highlights: string;
  };
  cameraMoves: string[];
  musicCue: string;
  accent: string;
  genreTags: string[];
};

export const TEMPLATE_ROOM_CATEGORIES: {
  id: TemplateRoomCategory;
  label: string;
  blurb: string;
  color: string;
}[] = [
  {
    id: "nollywood",
    label: "Nollywood · Nigeria",
    blurb: "Lagos melodrama, village intrigue, gospel bounce, street comedy — Nigeria film language.",
    color: "#FF7A00",
  },
  {
    id: "asia",
    label: "Asia Cinema",
    blurb: "K-drama emotion, Bollywood color, anime energy, C-drama wuxia, SEA street stories.",
    color: "#00D9FF",
  },
  {
    id: "drama",
    label: "Drama",
    blurb: "Intimate, emotional short scenes — confession, rupture, quiet power.",
    color: "#7C3AED",
  },
  {
    id: "action_thriller",
    label: "Action · Thriller",
    blurb: "Pulse cuts, pursuit, stakes — cinematic tension in under 60s.",
    color: "#FF7A00",
  },
  {
    id: "product_ad",
    label: "Product Ads",
    blurb: "Hero product intros — shelf to lifestyle to CTA in clean beats.",
    color: "#00D9FF",
  },
  {
    id: "intro",
    label: "Intros",
    blurb: "Cold opens & channel intros you can stamp on every episode.",
    color: "#C4B5FD",
  },
];

export const IDEAL_TEMPLATES: IdealTemplate[] = [
  // —— DRAMA ——
  {
    id: "drama-rain-confession",
    category: "drama",
    region: "global",
    name: "Rain Confession",
    tagline: "Two faces. One truth. Rain as witness.",
    durationSec: 45,
    aspectRatio: "2.39:1",
    mood: ["intimate", "wet neon", "slow burn"],
    lut: "Teal-Orange Soft Film",
    stylePreset: "A24 Intimate Drama",
    idealUse: "Relationship rupture / apology scenes for short films & series cold opens.",
    sampleScript:
      "INT. CAR — NIGHT\nRain hammers the windshield.\nSHE: I waited three years for you to say it.\nHE (beat): I know.\nClose on her hand leaving the door handle.",
    shots: [
      { atSec: 0, durationSec: 6, framing: "wide", camera: "static", note: "Car exterior, rain sheets, soft bokeh city" },
      { atSec: 6, durationSec: 10, framing: "medium", camera: "slow_push", note: "Two-shot through wet glass" },
      { atSec: 16, durationSec: 12, framing: "close", camera: "static", note: "Her eyes — dialogue land" },
      { atSec: 28, durationSec: 10, framing: "ecu", camera: "handheld_micro", note: "His mouth, unfinished sentence" },
      { atSec: 38, durationSec: 7, framing: "insert", camera: "static", note: "Hand leaves door — cut to black" },
    ],
    colorGrade: { contrast: 1.15, saturation: 0.85, temperature: -8, shadows: "#0a1628", highlights: "#f2e6d8" },
    cameraMoves: ["static", "slow_push", "handheld_micro"],
    musicCue: "Sparse piano + distant thunder bed",
    accent: "#7C3AED",
    genreTags: ["drama", "romance", "indie"],
  },
  {
    id: "drama-kitchen-ultimatum",
    category: "drama",
    region: "global",
    name: "Kitchen Ultimatum",
    tagline: "Domestic war at breakfast volume.",
    durationSec: 40,
    aspectRatio: "16:9",
    mood: ["claustrophobic", "daylight harsh", "quiet rage"],
    lut: "Bleach Bypass Day",
    stylePreset: "Kitchen Sink Realism",
    idealUse: "Family / marriage conflict beats for drama shorts.",
    sampleScript:
      "INT. KITCHEN — MORNING\nToaster pops.\nDAD: You’re not going.\nDAUGHTER: Watch me.\nShe slides the keys. He doesn’t stop her.",
    shots: [
      { atSec: 0, durationSec: 5, framing: "insert", camera: "static", note: "Toaster / kettle steam" },
      { atSec: 5, durationSec: 12, framing: "medium", camera: "locked_off", note: "Over-shoulder across table" },
      { atSec: 17, durationSec: 10, framing: "close", camera: "slow_push", note: "Daughter resolve" },
      { atSec: 27, durationSec: 8, framing: "wide", camera: "static", note: "Empty chair geometry" },
      { atSec: 35, durationSec: 5, framing: "insert", camera: "static", note: "Keys on wood — end" },
    ],
    colorGrade: { contrast: 1.25, saturation: 0.7, temperature: 6, shadows: "#1a1510", highlights: "#fff4e0" },
    cameraMoves: ["locked_off", "slow_push", "static"],
    musicCue: "None → single string swell at keys",
    accent: "#7C3AED",
    genreTags: ["drama", "family"],
  },
  {
    id: "drama-hospital-corridor",
    category: "drama",
    region: "global",
    name: "Corridor Aftermath",
    tagline: "The walk after the news.",
    durationSec: 35,
    aspectRatio: "16:9",
    mood: ["clinical", "grief", "fluorescent"],
    lut: "Hospital Cold",
    stylePreset: "Prestige TV Drama",
    idealUse: "Medical / loss drama interstitial for series.",
    sampleScript:
      "INT. HOSPITAL CORRIDOR — NIGHT\nHe exits the room. Doesn’t look back.\nNurse: Mr. Okonkwo—\nHe keeps walking. Exit sign flickers.",
    shots: [
      { atSec: 0, durationSec: 8, framing: "wide", camera: "tracking_back", note: "Long corridor pull" },
      { atSec: 8, durationSec: 10, framing: "medium", camera: "side_track", note: "Profile walk" },
      { atSec: 18, durationSec: 9, framing: "close", camera: "static", note: "Nurse call ignored" },
      { atSec: 27, durationSec: 8, framing: "wide", camera: "static", note: "Exit sign — he disappears" },
    ],
    colorGrade: { contrast: 1.1, saturation: 0.55, temperature: -12, shadows: "#0d1520", highlights: "#dce8f0" },
    cameraMoves: ["tracking_back", "side_track", "static"],
    musicCue: "Low drone + distant PA",
    accent: "#7C3AED",
    genreTags: ["drama", "medical"],
  },

  // —— ACTION / THRILLER ——
  {
    id: "action-alley-pursuit",
    category: "action_thriller",
    region: "global",
    name: "Alley Pursuit",
    tagline: "Foot chase. Neon puddles. No breath left.",
    durationSec: 50,
    aspectRatio: "2.39:1",
    mood: ["kinetic", "night city", "threat"],
    lut: "Neon Thriller Crush",
    stylePreset: "Night Runner Thriller",
    idealUse: "Action cold open / chase beat for thriller shorts.",
    sampleScript:
      "EXT. ALLEY — NIGHT\nShe runs. Boots splash.\nRADIO: Do not engage—\nA shadow cuts the exit. She vaults the fence.",
    shots: [
      { atSec: 0, durationSec: 4, framing: "ecu", camera: "whip_pan", note: "Eyes snap open / startle" },
      { atSec: 4, durationSec: 8, framing: "wide", camera: "crane_drop", note: "Alley establish, pursuer enter" },
      { atSec: 12, durationSec: 12, framing: "medium", camera: "run_cam", note: "Handheld chase through steam" },
      { atSec: 24, durationSec: 8, framing: "insert", camera: "static", note: "Boot splash / fence hand" },
      { atSec: 32, durationSec: 10, framing: "wide", camera: "crash_zoom", note: "Exit blocked — decision" },
      { atSec: 42, durationSec: 8, framing: "close", camera: "dutch", note: "Vault — smash cut" },
    ],
    colorGrade: { contrast: 1.35, saturation: 1.1, temperature: -5, shadows: "#050510", highlights: "#ff4d6d" },
    cameraMoves: ["whip_pan", "run_cam", "crash_zoom", "dutch"],
    musicCue: "Percussion chase + siren tail",
    accent: "#FF7A00",
    genreTags: ["action", "thriller", "chase"],
  },
  {
    id: "thriller-safehouse-breach",
    category: "action_thriller",
    region: "global",
    name: "Safehouse Breach",
    tagline: "Silence. Then the door.",
    durationSec: 42,
    aspectRatio: "16:9",
    mood: ["suspense", "tight space", "countdown"],
    lut: "Green Shadow Thriller",
    stylePreset: "Breach & Clear",
    idealUse: "Heist / spy thriller entry beat.",
    sampleScript:
      "INT. SAFEHOUSE — NIGHT\nTimer: 00:12.\nHe chambers a round.\nDoor handle turns. Blackout.",
    shots: [
      { atSec: 0, durationSec: 6, framing: "insert", camera: "static", note: "Digital timer close" },
      { atSec: 6, durationSec: 10, framing: "medium", camera: "slow_orbit", note: "Agent prep" },
      { atSec: 16, durationSec: 8, framing: "ecu", camera: "static", note: "Door handle turning" },
      { atSec: 24, durationSec: 10, framing: "wide", camera: "snap_zoom", note: "Breach silhouette" },
      { atSec: 34, durationSec: 8, framing: "close", camera: "handheld", note: "Muzzle flash — cut to black" },
    ],
    colorGrade: { contrast: 1.4, saturation: 0.75, temperature: -10, shadows: "#0a1a12", highlights: "#c8ffd0" },
    cameraMoves: ["slow_orbit", "snap_zoom", "handheld"],
    musicCue: "Heartbeat pulse → stinger",
    accent: "#FF7A00",
    genreTags: ["thriller", "spy", "heist"],
  },
  {
    id: "action-rooftop-standoff",
    category: "action_thriller",
    region: "global",
    name: "Rooftop Standoff",
    tagline: "Two guns. One skyline. Wind decides.",
    durationSec: 38,
    aspectRatio: "2.39:1",
    mood: ["epic", "wind", "duel"],
    lut: "Golden Hour Crush",
    stylePreset: "Skyline Duel",
    idealUse: "Finale tease or mid-series cliffhanger.",
    sampleScript:
      "EXT. ROOFTOP — SUNSET\nThey face each other.\nHERO: Walk away.\nANTAGONIST: You first.\nHelicopter wash hits — freeze frame.",
    shots: [
      { atSec: 0, durationSec: 7, framing: "extreme_wide", camera: "drone_push", note: "Skyline establish" },
      { atSec: 7, durationSec: 10, framing: "medium", camera: "side_track", note: "Two-shot profile" },
      { atSec: 17, durationSec: 8, framing: "close", camera: "static", note: "Dialogue exchange" },
      { atSec: 25, durationSec: 8, framing: "wide", camera: "orbit", note: "Helicopter enter frame" },
      { atSec: 33, durationSec: 5, framing: "medium", camera: "freeze", note: "Title card freeze" },
    ],
    colorGrade: { contrast: 1.2, saturation: 1.05, temperature: 18, shadows: "#1a0a08", highlights: "#ffd4a8" },
    cameraMoves: ["drone_push", "orbit", "side_track"],
    musicCue: "Brass sting + rotor wash",
    accent: "#FF7A00",
    genreTags: ["action", "thriller"],
  },

  // —— PRODUCT ADS ——
  {
    id: "ad-product-hero-orbit",
    category: "product_ad",
    region: "global",
    name: "Hero Product Orbit",
    tagline: "Shelf → glow → lifestyle → CTA.",
    durationSec: 30,
    aspectRatio: "9:16",
    mood: ["premium", "clean", "aspire"],
    lut: "Commerce Soft Pop",
    stylePreset: "DTC Hero Reel",
    idealUse: "Product launch / Amazon / TikTok shop intros.",
    sampleScript:
      "VO: Meet the bottle that travels with you.\nOn-screen: HYDRATE · 24H COLD\nCTA: Shop now — link in bio.",
    shots: [
      { atSec: 0, durationSec: 5, framing: "close", camera: "orbit", note: "Product on black, rim light" },
      { atSec: 5, durationSec: 6, framing: "ecu", camera: "macro_slide", note: "Texture / logo detail" },
      { atSec: 11, durationSec: 8, framing: "medium", camera: "steadicam", note: "Lifestyle handoff outdoor" },
      { atSec: 19, durationSec: 6, framing: "wide", camera: "static", note: "Pack shot + benefit chips" },
      { atSec: 25, durationSec: 5, framing: "graphic", camera: "static", note: "CTA end card" },
    ],
    colorGrade: { contrast: 1.05, saturation: 1.15, temperature: 4, shadows: "#101018", highlights: "#ffffff" },
    cameraMoves: ["orbit", "macro_slide", "steadicam"],
    musicCue: "Upbeat lo-fi bed + whoosh hits",
    accent: "#00D9FF",
    genreTags: ["ad", "product", "dtc", "vertical"],
  },
  {
    id: "ad-unboxing-reveal",
    category: "product_ad",
    region: "global",
    name: "Unboxing Reveal",
    tagline: "Hands. Tape. First light on the product.",
    durationSec: 28,
    aspectRatio: "9:16",
    mood: ["ASMR", "anticipation", "handcraft"],
    lut: "Warm Unbox",
    stylePreset: "Creator Unbox",
    idealUse: "Influencer / UGC style product introduction.",
    sampleScript:
      "VO (soft): Okay… this is the one.\nCut tape. Lift lid.\nVO: Worth the wait.",
    shots: [
      { atSec: 0, durationSec: 5, framing: "top_down", camera: "static", note: "Box on linen" },
      { atSec: 5, durationSec: 7, framing: "close", camera: "slow_push", note: "Hands cut tape" },
      { atSec: 12, durationSec: 8, framing: "ecu", camera: "static", note: "Product lift reveal" },
      { atSec: 20, durationSec: 8, framing: "medium", camera: "orbit", note: "Held to camera + smile" },
    ],
    colorGrade: { contrast: 1.0, saturation: 1.05, temperature: 10, shadows: "#1c1410", highlights: "#fff8f0" },
    cameraMoves: ["static", "slow_push", "orbit"],
    musicCue: "Soft plucks + paper ASMR",
    accent: "#00D9FF",
    genreTags: ["ad", "ugc", "unboxing"],
  },
  {
    id: "ad-problem-solution",
    category: "product_ad",
    region: "global",
    name: "Problem → Solution",
    tagline: "Pain in 8s. Fix in 12s. Proof in 5s.",
    durationSec: 25,
    aspectRatio: "16:9",
    mood: ["direct", "clear", "conversion"],
    lut: "High Key Commerce",
    stylePreset: "Performance Ad",
    idealUse: "Meta/YouTube performance ads for SaaS or physical goods.",
    sampleScript:
      "HOOK: Still losing hours to [pain]?\nDEMO: One tap. Done.\nPROOF: 12,000 teams.\nCTA: Start free.",
    shots: [
      { atSec: 0, durationSec: 5, framing: "close", camera: "snap_zoom", note: "Frustrated face / chaos B-roll" },
      { atSec: 5, durationSec: 8, framing: "screen", camera: "static", note: "UI / product demo" },
      { atSec: 13, durationSec: 6, framing: "medium", camera: "static", note: "Happy outcome" },
      { atSec: 19, durationSec: 6, framing: "graphic", camera: "static", note: "CTA + logo" },
    ],
    colorGrade: { contrast: 1.1, saturation: 1.2, temperature: 2, shadows: "#0a0a12", highlights: "#f0f4ff" },
    cameraMoves: ["snap_zoom", "static"],
    musicCue: "Punchy electronic bed",
    accent: "#00D9FF",
    genreTags: ["ad", "performance", "saas"],
  },
  {
    id: "ad-luxury-still-life",
    category: "product_ad",
    region: "global",
    name: "Luxury Still Life",
    tagline: "One light. One object. Infinite desire.",
    durationSec: 20,
    aspectRatio: "1:1",
    mood: ["editorial", "minimal", "expensive"],
    lut: "Fashion Soft Contrast",
    stylePreset: "Luxury Pack Shot",
    idealUse: "Beauty / fragrance / jewelry brand films.",
    sampleScript:
      "No VO. Text only: CRAFTED · LIMITED.\nEnd card: Discover the collection.",
    shots: [
      { atSec: 0, durationSec: 6, framing: "close", camera: "macro_slide", note: "Surface gleam" },
      { atSec: 6, durationSec: 8, framing: "medium", camera: "orbit", note: "Full product hero" },
      { atSec: 14, durationSec: 6, framing: "graphic", camera: "static", note: "Wordmark end" },
    ],
    colorGrade: { contrast: 1.18, saturation: 0.9, temperature: -2, shadows: "#0c0c0c", highlights: "#f5f0ea" },
    cameraMoves: ["macro_slide", "orbit"],
    musicCue: "Ambient pad only",
    accent: "#00D9FF",
    genreTags: ["ad", "luxury", "beauty"],
  },

  // —— INTROS ——
  {
    id: "intro-channel-stamp",
    category: "intro",
    region: "global",
    name: "Channel Stamp",
    tagline: "Logo hit in 4 seconds — every episode.",
    durationSec: 8,
    aspectRatio: "16:9",
    mood: ["brand", "punchy", "repeatable"],
    lut: "Brand Neutral",
    stylePreset: "Series Open Bumper",
    idealUse: "YouTube / series episode intro bumper.",
    sampleScript:
      "SFX: Whoosh + hit.\nLOGO: REELSTORM / YOUR BRAND\nTAG: Your story. Your empire.",
    shots: [
      { atSec: 0, durationSec: 2, framing: "graphic", camera: "glitch", note: "Noise → shape form" },
      { atSec: 2, durationSec: 3, framing: "logo", camera: "impact", note: "Logo slam" },
      { atSec: 5, durationSec: 3, framing: "graphic", camera: "static", note: "Tagline hold" },
    ],
    colorGrade: { contrast: 1.2, saturation: 1.0, temperature: 0, shadows: "#080808", highlights: "#ffffff" },
    cameraMoves: ["glitch", "impact"],
    musicCue: "Signature stinger 1.2s",
    accent: "#C4B5FD",
    genreTags: ["intro", "bumper", "brand"],
  },
  {
    id: "intro-cold-open-mystery",
    category: "intro",
    region: "global",
    name: "Cold Open Mystery",
    tagline: "Start mid-crime. Titles later.",
    durationSec: 15,
    aspectRatio: "16:9",
    mood: ["hook", "mystery", "binge"],
    lut: "Desaturated Hook",
    stylePreset: "Prestige Cold Open",
    idealUse: "Episode cold open before title sequence.",
    sampleScript:
      "EXT. STREET — NIGHT\nA phone rings once. Stopped.\nFOOTSTEPS approach.\nTITLE: EPISODE 03 — THE CALL",
    shots: [
      { atSec: 0, durationSec: 4, framing: "insert", camera: "static", note: "Phone ring visual" },
      { atSec: 4, durationSec: 5, framing: "wide", camera: "slow_push", note: "Empty street tension" },
      { atSec: 9, durationSec: 3, framing: "close", camera: "static", note: "Footsteps enter frame" },
      { atSec: 12, durationSec: 3, framing: "graphic", camera: "static", note: "Episode title card" },
    ],
    colorGrade: { contrast: 1.3, saturation: 0.6, temperature: -6, shadows: "#050508", highlights: "#e8e8f0" },
    cameraMoves: ["slow_push", "static"],
    musicCue: "Silence → single note",
    accent: "#C4B5FD",
    genreTags: ["intro", "cold-open", "series"],
  },
  {
    id: "intro-speaker-walkup",
    category: "intro",
    region: "global",
    name: "Speaker Walk-Up",
    tagline: "Host enters. Authority locks.",
    durationSec: 12,
    aspectRatio: "16:9",
    mood: ["confident", "talking-head", "pro"],
    lut: "Talk Show Warm",
    stylePreset: "Host Entrance",
    idealUse: "Podcast / academy lecture / brand host intro.",
    sampleScript:
      "HOST walks into frame.\nHOST: Today we break the system that keeps creators stuck.\nLower-third: NAME · TITLE",
    shots: [
      { atSec: 0, durationSec: 4, framing: "wide", camera: "tracking", note: "Walk into set" },
      { atSec: 4, durationSec: 5, framing: "medium", camera: "static", note: "Address camera" },
      { atSec: 9, durationSec: 3, framing: "graphic", camera: "static", note: "Lower-third + topic" },
    ],
    colorGrade: { contrast: 1.08, saturation: 1.0, temperature: 8, shadows: "#121018", highlights: "#fff5ea" },
    cameraMoves: ["tracking", "static"],
    musicCue: "Bed under VO, duck on first line",
    accent: "#C4B5FD",
    genreTags: ["intro", "host", "academy"],
  },
  {
    id: "intro-title-kinetic",
    category: "intro",
    region: "global",
    name: "Kinetic Title Storm",
    tagline: "Typography as the action.",
    durationSec: 10,
    aspectRatio: "16:9",
    mood: ["graphic", "energy", "modern"],
    lut: "High Contrast Type",
    stylePreset: "Motion Title",
    idealUse: "Trailer title card / course module intro.",
    sampleScript:
      "WORDS SLAM: BUILD · LOCK · VAULT · MERGE\nFinal: REELSTORM ACADEMY",
    shots: [
      { atSec: 0, durationSec: 2.5, framing: "type", camera: "impact", note: "BUILD" },
      { atSec: 2.5, durationSec: 2.5, framing: "type", camera: "impact", note: "LOCK" },
      { atSec: 5, durationSec: 2.5, framing: "type", camera: "impact", note: "VAULT" },
      { atSec: 7.5, durationSec: 2.5, framing: "logo", camera: "impact", note: "Brand lockup" },
    ],
    colorGrade: { contrast: 1.4, saturation: 0.8, temperature: 0, shadows: "#000000", highlights: "#ffffff" },
    cameraMoves: ["impact"],
    musicCue: "Four hits synced to words",
    accent: "#C4B5FD",
    genreTags: ["intro", "motion", "title"],
  },
  // —— NOLLYWOOD · NIGERIA ——
  {
    id: "nlw-lagos-family-reveal",
    category: "nollywood",
    region: "nigeria",
    name: "Lagos Family Reveal",
    tagline: "Living-room confrontation — auntie knows everything.",
    durationSec: 45,
    aspectRatio: "16:9",
    mood: ["melodrama", "warm", "tense"],
    lut: "Nollywood Warm Gold",
    stylePreset: "nollywood_drama",
    idealUse: "Family saga teasers, YouTube Nollywood shorts, WhatsApp drama clips.",
    sampleScript: "AUNTIE: So this is the girl you bring home? MAMA: Sit down. We talk as family.",
    shots: [
      { atSec: 0, durationSec: 5, framing: "wide", camera: "static", note: "Lagos sitting room — ankara, framed photos" },
      { atSec: 5, durationSec: 8, framing: "medium", camera: "slow_push", note: "Auntie enters; room freezes" },
      { atSec: 13, durationSec: 10, framing: "close", camera: "static", note: "Daughter eyes — guilt" },
      { atSec: 23, durationSec: 10, framing: "two_shot", camera: "orbit", note: "Mother vs auntie crossfire" },
      { atSec: 33, durationSec: 12, framing: "close", camera: "handheld", note: "Phone slip — WhatsApp screenshot" },
    ],
    colorGrade: { contrast: 1.15, saturation: 1.2, temperature: 18, shadows: "#2a1810", highlights: "#ffe8c8" },
    cameraMoves: ["static", "slow_push", "orbit", "handheld"],
    musicCue: "Highlife soft pad → sharp silence on reveal",
    accent: "#FF7A00",
    genreTags: ["nollywood", "nigeria", "family", "lagos", "drama"],
  },
  {
    id: "nlw-village-return",
    category: "nollywood",
    region: "nigeria",
    name: "Village Return",
    tagline: "City boy steps into red earth — elders wait.",
    durationSec: 40,
    aspectRatio: "2.39:1",
    mood: ["epic", "dust", "heritage"],
    lut: "Harmattan Dust",
    stylePreset: "nollywood_epic",
    idealUse: "Homecoming trailers, cultural shorts, diaspora hooks.",
    sampleScript: "ELDER: The land remembers you. SON: I only came for three days.",
    shots: [
      { atSec: 0, durationSec: 6, framing: "wide", camera: "drone_descend", note: "Compound roofs, goats, harmattan haze" },
      { atSec: 6, durationSec: 8, framing: "medium", camera: "tracking", note: "Footsteps on red soil" },
      { atSec: 14, durationSec: 10, framing: "close", camera: "slow_push", note: "Elder eyes under agbada" },
      { atSec: 24, durationSec: 8, framing: "wide", camera: "static", note: "Family lined on veranda" },
      { atSec: 32, durationSec: 8, framing: "close", camera: "static", note: "Handshake that lasts too long" },
    ],
    colorGrade: { contrast: 1.2, saturation: 1.05, temperature: 22, shadows: "#3a2818", highlights: "#f5e6c8" },
    cameraMoves: ["drone_descend", "tracking", "slow_push", "static"],
    musicCue: "Talking drum + sparse strings",
    accent: "#C4A35A",
    genreTags: ["nollywood", "village", "yoruba", "heritage", "nigeria"],
  },
  {
    id: "nlw-market-chase",
    category: "nollywood",
    region: "nigeria",
    name: "Balogun Market Chase",
    tagline: "Purse snatch through fabric alleys — Lagos kinetic.",
    durationSec: 35,
    aspectRatio: "9:16",
    mood: ["urgent", "street", "comic-tension"],
    lut: "Street Neon Lagos",
    stylePreset: "nollywood_action",
    idealUse: "TikTok action comedy, Nollywood street shorts.",
    sampleScript: "THIEF: Move! SELLER: Ole! Catch am!",
    shots: [
      { atSec: 0, durationSec: 4, framing: "pov", camera: "run", note: "Crowd blur — market entrance" },
      { atSec: 4, durationSec: 8, framing: "handheld", camera: "chase", note: "Weave past wrappers & okada" },
      { atSec: 12, durationSec: 6, framing: "wide", camera: "whip_pan", note: "Crowd points" },
      { atSec: 18, durationSec: 8, framing: "close", camera: "snap_zoom", note: "Bag drops — spilled tomatoes" },
      { atSec: 26, durationSec: 9, framing: "medium", camera: "static", note: "Caught — comic freeze" },
    ],
    colorGrade: { contrast: 1.25, saturation: 1.3, temperature: 12, shadows: "#1a1020", highlights: "#ffd080" },
    cameraMoves: ["run", "chase", "whip_pan", "snap_zoom"],
    musicCue: "Afrobeats percussion chase loop",
    accent: "#FF7A00",
    genreTags: ["nollywood", "lagos", "action", "comedy", "market"],
  },
  {
    id: "nlw-gospel-testimony",
    category: "nollywood",
    region: "nigeria",
    name: "Gospel Testimony Open",
    tagline: "Testimony night — light, tears, choir swell.",
    durationSec: 30,
    aspectRatio: "16:9",
    mood: ["uplift", "faith", "glow"],
    lut: "Cathedral Gold",
    stylePreset: "nollywood_gospel",
    idealUse: "Church media, gospel YouTube intros, faith shorts.",
    sampleScript: "SISTER: I almost gave up. Tonight I stand because God…",
    shots: [
      { atSec: 0, durationSec: 5, framing: "wide", camera: "crane_up", note: "Church interior — warm spots" },
      { atSec: 5, durationSec: 8, framing: "medium", camera: "slow_push", note: "Testimony mic" },
      { atSec: 13, durationSec: 7, framing: "close", camera: "static", note: "Tear catch light" },
      { atSec: 20, durationSec: 5, framing: "wide", camera: "orbit", note: "Choir rises" },
      { atSec: 25, durationSec: 5, framing: "title", camera: "impact", note: "Series title card" },
    ],
    colorGrade: { contrast: 1.1, saturation: 1.15, temperature: 15, shadows: "#1a1028", highlights: "#ffe8a0" },
    cameraMoves: ["crane_up", "slow_push", "orbit", "impact"],
    musicCue: "Soft organ → choir hit",
    accent: "#7C3AED",
    genreTags: ["nollywood", "gospel", "church", "nigeria", "testimony"],
  },
  {
    id: "nlw-yahoo-sting",
    category: "nollywood",
    region: "nigeria",
    name: "Yahoo Sting Night",
    tagline: "Blue laptop glow — the deal goes wrong.",
    durationSec: 38,
    aspectRatio: "16:9",
    mood: ["noir", "tension", "moral"],
    lut: "Cyber Blue Lagos",
    stylePreset: "nollywood_thriller",
    idealUse: "Crime drama teasers, moral-warning shorts.",
    sampleScript: "GUY: Money don enter. FRIEND: Check your door.",
    shots: [
      { atSec: 0, durationSec: 6, framing: "close", camera: "static", note: "Laptop screen reflected in eyes" },
      { atSec: 6, durationSec: 8, framing: "medium", camera: "slow_push", note: "Two guys in dark room" },
      { atSec: 14, durationSec: 8, framing: "wide", camera: "handheld", note: "Knock at door" },
      { atSec: 22, durationSec: 8, framing: "pov", camera: "snap_zoom", note: "Phone flash — EFCC vibe" },
      { atSec: 30, durationSec: 8, framing: "close", camera: "static", note: "Freeze on guilt face" },
    ],
    colorGrade: { contrast: 1.35, saturation: 0.85, temperature: -10, shadows: "#050510", highlights: "#60a5fa" },
    cameraMoves: ["static", "slow_push", "handheld", "snap_zoom"],
    musicCue: "Low bass pulse + phone vibrate sync",
    accent: "#00D9FF",
    genreTags: ["nollywood", "thriller", "crime", "lagos", "nigeria"],
  },
  {
    id: "nlw-owambe-entrance",
    category: "nollywood",
    region: "nigeria",
    name: "Owambe Entrance",
    tagline: "Aso-ebi arrival — geles, cameras, soft life.",
    durationSec: 28,
    aspectRatio: "9:16",
    mood: ["glam", "celebration", "fashion"],
    lut: "Owambe Pop",
    stylePreset: "nollywood_lifestyle",
    idealUse: "Event reels, fashion brands, wedding content.",
    sampleScript: "MC: The bride's people are here! Crowd cheers.",
    shots: [
      { atSec: 0, durationSec: 4, framing: "detail", camera: "tilt_up", note: "Gele + gold jewelry" },
      { atSec: 4, durationSec: 6, framing: "full", camera: "tracking", note: "Walk into hall" },
      { atSec: 10, durationSec: 6, framing: "wide", camera: "orbit", note: "Dance floor reaction" },
      { atSec: 16, durationSec: 6, framing: "medium", camera: "slow_mo", note: "Spray money moment" },
      { atSec: 22, durationSec: 6, framing: "logo", camera: "impact", note: "Brand / event lockup" },
    ],
    colorGrade: { contrast: 1.2, saturation: 1.4, temperature: 10, shadows: "#201018", highlights: "#ffe0f0" },
    cameraMoves: ["tilt_up", "tracking", "orbit", "slow_mo", "impact"],
    musicCue: "Afrobeats drop on entrance",
    accent: "#FF7A00",
    genreTags: ["nollywood", "owambe", "fashion", "wedding", "nigeria"],
  },
  {
    id: "nlw-kannywood-courtyard",
    category: "nollywood",
    region: "nigeria",
    name: "Kannywood Courtyard",
    tagline: "Kano courtyard — honor, veil, quiet storm.",
    durationSec: 42,
    aspectRatio: "16:9",
    mood: ["dignified", "romance", "restraint"],
    lut: "Sahel Soft",
    stylePreset: "kannywood_drama",
    idealUse: "Hausa drama shorts, northern Nigeria series teasers.",
    sampleScript: "HE: I ask your father again. SHE: Pray first. Then come.",
    shots: [
      { atSec: 0, durationSec: 6, framing: "wide", camera: "static", note: "Courtyard afternoon light" },
      { atSec: 6, durationSec: 10, framing: "medium", camera: "slow_push", note: "Conversation at doorway" },
      { atSec: 16, durationSec: 8, framing: "close", camera: "static", note: "Eyes meet — cutaway henna" },
      { atSec: 24, durationSec: 10, framing: "two_shot", camera: "orbit", note: "Father appears in frame edge" },
      { atSec: 34, durationSec: 8, framing: "wide", camera: "fade", note: "Call to prayer ambience" },
    ],
    colorGrade: { contrast: 1.05, saturation: 0.95, temperature: 20, shadows: "#2a2418", highlights: "#f0e8d0" },
    cameraMoves: ["static", "slow_push", "orbit"],
    musicCue: "Kora / soft Hausa melody",
    accent: "#C4A35A",
    genreTags: ["kannywood", "hausa", "nigeria", "romance", "drama"],
  },
  {
    id: "nlw-naija-brand-ad",
    category: "nollywood",
    region: "nigeria",
    name: "Naija Brand Ad",
    tagline: "From stall to soft life — product in 25s.",
    durationSec: 25,
    aspectRatio: "9:16",
    mood: ["aspirational", "bright", "local"],
    lut: "Naija Pop Ad",
    stylePreset: "naija_product",
    idealUse: "FMCG, fintech, telco, skincare ads for Nigerian audiences.",
    sampleScript: "VO: From hustle to soft life — one tap.",
    shots: [
      { atSec: 0, durationSec: 4, framing: "product", camera: "hero_spin", note: "Product on ankara cloth" },
      { atSec: 4, durationSec: 6, framing: "lifestyle", camera: "tracking", note: "Young woman in Lagos traffic smile" },
      { atSec: 10, durationSec: 5, framing: "detail", camera: "macro", note: "App / pour / unbox" },
      { atSec: 15, durationSec: 5, framing: "group", camera: "orbit", note: "Friends celebrate" },
      { atSec: 20, durationSec: 5, framing: "logo", camera: "impact", note: "CTA + price / USSD" },
    ],
    colorGrade: { contrast: 1.15, saturation: 1.35, temperature: 8, shadows: "#101018", highlights: "#ffffff" },
    cameraMoves: ["hero_spin", "tracking", "macro", "orbit", "impact"],
    musicCue: "Afrobeats 8-bar brand bed",
    accent: "#00D9FF",
    genreTags: ["nigeria", "ad", "product", "naija", "fmcg"],
  },
  // —— ASIA CINEMA ——
  {
    id: "asia-kdrama-rain-bus",
    category: "asia",
    region: "asia",
    name: "K-Drama Rain Bus Stop",
    tagline: "Shared umbrella — slow confession energy.",
    durationSec: 40,
    aspectRatio: "16:9",
    mood: ["bittersweet", "soft", "romantic"],
    lut: "Seoul Soft Teal",
    stylePreset: "kdrama_romance",
    idealUse: "K-drama style shorts, romance trailers, OST moments.",
    sampleScript: "HE: You'll catch a cold. SHE: Then stand closer.",
    shots: [
      { atSec: 0, durationSec: 6, framing: "wide", camera: "static", note: "Bus stop neon in rain" },
      { atSec: 6, durationSec: 10, framing: "medium", camera: "slow_push", note: "Umbrella share" },
      { atSec: 16, durationSec: 8, framing: "close", camera: "static", note: "Eye contact — rain drops" },
      { atSec: 24, durationSec: 8, framing: "two_shot", camera: "orbit", note: "Almost-kiss interrupt — bus arrives" },
      { atSec: 32, durationSec: 8, framing: "wide", camera: "fade", note: "She boards; he stays" },
    ],
    colorGrade: { contrast: 1.1, saturation: 0.9, temperature: -8, shadows: "#0a1820", highlights: "#c8e8f0" },
    cameraMoves: ["static", "slow_push", "orbit"],
    musicCue: "Piano OST swell + rain bed",
    accent: "#00D9FF",
    genreTags: ["kdrama", "korea", "romance", "asia", "soft"],
  },
  {
    id: "asia-bollywood-item-hook",
    category: "asia",
    region: "asia",
    name: "Bollywood Color Hook",
    tagline: "Festival color burst — dance cut on beat.",
    durationSec: 30,
    aspectRatio: "16:9",
    mood: ["joyful", "saturated", "dance"],
    lut: "Bollywood Punch",
    stylePreset: "bollywood_dance",
    idealUse: "Song promos, wedding reels, brand festival ads.",
    sampleScript: "VO: One night. One song. Everyone dances.",
    shots: [
      { atSec: 0, durationSec: 4, framing: "wide", camera: "crane_up", note: "Crowd + marigold" },
      { atSec: 4, durationSec: 6, framing: "full", camera: "orbit", note: "Lead dancer spin" },
      { atSec: 10, durationSec: 6, framing: "close", camera: "snap_zoom", note: "Eye makeup + smile" },
      { atSec: 16, durationSec: 7, framing: "group", camera: "whip_pan", note: "Synchronized chorus" },
      { atSec: 23, durationSec: 7, framing: "wide", camera: "slow_mo", note: "Confetti freeze" },
    ],
    colorGrade: { contrast: 1.25, saturation: 1.5, temperature: 15, shadows: "#201010", highlights: "#ffe0a0" },
    cameraMoves: ["crane_up", "orbit", "snap_zoom", "whip_pan", "slow_mo"],
    musicCue: "Dhol + synth drop on cuts",
    accent: "#FF7A00",
    genreTags: ["bollywood", "india", "dance", "asia", "festival"],
  },
  {
    id: "asia-anime-power-awaken",
    category: "asia",
    region: "asia",
    name: "Anime Power Awaken",
    tagline: "Speed lines, aura bloom — shonen beat.",
    durationSec: 25,
    aspectRatio: "16:9",
    mood: ["intense", "heroic", "stylized"],
    lut: "Anime Cel Punch",
    stylePreset: "anime_action",
    idealUse: "Anime-style shorts, game trailers, YouTube cold opens.",
    sampleScript: "HERO: Not this time. Aura erupts.",
    shots: [
      { atSec: 0, durationSec: 3, framing: "close", camera: "impact", note: "Eye open — flash" },
      { atSec: 3, durationSec: 5, framing: "medium", camera: "dutch", note: "Stance + wind" },
      { atSec: 8, durationSec: 6, framing: "wide", camera: "orbit", note: "Aura bloom + speed lines" },
      { atSec: 14, durationSec: 6, framing: "action", camera: "whip_pan", note: "Clash impact frame" },
      { atSec: 20, durationSec: 5, framing: "title", camera: "impact", note: "Series kanji / title card" },
    ],
    colorGrade: { contrast: 1.4, saturation: 1.2, temperature: 0, shadows: "#100820", highlights: "#ffffff" },
    cameraMoves: ["impact", "dutch", "orbit", "whip_pan"],
    musicCue: "Orchestra stab + rock guitar",
    accent: "#7C3AED",
    genreTags: ["anime", "japan", "shonen", "asia", "action"],
  },
  {
    id: "asia-cdrama-wuxia-rooftop",
    category: "asia",
    region: "asia",
    name: "C-Drama Wuxia Rooftop",
    tagline: "Moonlit tiles — sword, silk, silence.",
    durationSec: 45,
    aspectRatio: "2.39:1",
    mood: ["mythic", "elegant", "lethal"],
    lut: "Wuxia Moon Silver",
    stylePreset: "cdrama_wuxia",
    idealUse: "Wuxia trailers, historical fantasy shorts.",
    sampleScript: "HEROINE: Leave the mountain. Or draw.",
    shots: [
      { atSec: 0, durationSec: 7, framing: "wide", camera: "crane_down", note: "Rooftops under moon" },
      { atSec: 7, durationSec: 10, framing: "medium", camera: "tracking", note: "Silk sleeve in wind" },
      { atSec: 17, durationSec: 10, framing: "two_shot", camera: "orbit", note: "Standoff" },
      { atSec: 27, durationSec: 10, framing: "action", camera: "slow_mo", note: "Blade spark" },
      { atSec: 37, durationSec: 8, framing: "close", camera: "static", note: "Blood on petal" },
    ],
    colorGrade: { contrast: 1.2, saturation: 0.85, temperature: -5, shadows: "#081018", highlights: "#d0e0f0" },
    cameraMoves: ["crane_down", "tracking", "orbit", "slow_mo"],
    musicCue: "Guqin + low drone",
    accent: "#C4B5FD",
    genreTags: ["cdrama", "wuxia", "china", "asia", "fantasy"],
  },
  {
    id: "asia-thai-street-food",
    category: "asia",
    region: "asia",
    name: "Thai Street Food Night",
    tagline: "Steam, neon, first bite — Bangkok hunger.",
    durationSec: 28,
    aspectRatio: "9:16",
    mood: ["mouthwatering", "night", "travel"],
    lut: "Bangkok Neon Food",
    stylePreset: "sea_food_ad",
    idealUse: "Food reels, travel ads, restaurant promos SEA.",
    sampleScript: "VO: One alley. Ten flavors. Start here.",
    shots: [
      { atSec: 0, durationSec: 4, framing: "wide", camera: "tracking", note: "Night market alley" },
      { atSec: 4, durationSec: 6, framing: "macro", camera: "slow_push", note: "Wok flame + steam" },
      { atSec: 10, durationSec: 6, framing: "close", camera: "static", note: "First bite reaction" },
      { atSec: 16, durationSec: 6, framing: "medium", camera: "orbit", note: "Friends share plate" },
      { atSec: 22, durationSec: 6, framing: "logo", camera: "impact", note: "Map pin / brand" },
    ],
    colorGrade: { contrast: 1.2, saturation: 1.35, temperature: 5, shadows: "#100818", highlights: "#ffc080" },
    cameraMoves: ["tracking", "slow_push", "orbit", "impact"],
    musicCue: "Light SEA pop + sizzle foley",
    accent: "#FF7A00",
    genreTags: ["thai", "food", "sea", "asia", "travel"],
  },
  {
    id: "asia-pinoy-teleserye",
    category: "asia",
    region: "asia",
    name: "Pinoy Teleserye Twist",
    tagline: "Living room gasp — the twin returns.",
    durationSec: 35,
    aspectRatio: "16:9",
    mood: ["melodrama", "twist", "soap"],
    lut: "Manila Warm Drama",
    stylePreset: "teleserye_drama",
    idealUse: "Filipino drama teasers, soap-style shorts.",
    sampleScript: "MOTHER: Impossible… you died in the fire.",
    shots: [
      { atSec: 0, durationSec: 5, framing: "wide", camera: "static", note: "Family living room" },
      { atSec: 5, durationSec: 8, framing: "medium", camera: "slow_push", note: "Door opens — silhouette" },
      { atSec: 13, durationSec: 8, framing: "close", camera: "snap_zoom", note: "Mother reaction" },
      { atSec: 21, durationSec: 7, framing: "two_shot", camera: "handheld", note: "Embrace / push away" },
      { atSec: 28, durationSec: 7, framing: "title", camera: "impact", note: "Title sting" },
    ],
    colorGrade: { contrast: 1.15, saturation: 1.1, temperature: 12, shadows: "#201818", highlights: "#ffe8d0" },
    cameraMoves: ["static", "slow_push", "snap_zoom", "handheld", "impact"],
    musicCue: "Soap sting strings + heartbeat",
    accent: "#7C3AED",
    genreTags: ["filipino", "teleserye", "asia", "drama", "twist"],
  },
  {
    id: "asia-indo-sinetron-rival",
    category: "asia",
    region: "asia",
    name: "Sinetron Rival Glance",
    tagline: "Jakarta office — smile that cuts.",
    durationSec: 32,
    aspectRatio: "16:9",
    mood: ["glam", "rivalry", "office"],
    lut: "Jakarta Gloss",
    stylePreset: "sinetron_drama",
    idealUse: "Indonesian drama promos, rivalry shorts.",
    sampleScript: "RIVAL: Welcome back. Try not to fall this time.",
    shots: [
      { atSec: 0, durationSec: 5, framing: "wide", camera: "tracking", note: "Glass office corridor" },
      { atSec: 5, durationSec: 8, framing: "medium", camera: "slow_push", note: "Two women face-off" },
      { atSec: 13, durationSec: 7, framing: "close", camera: "static", note: "Smile / micro expression" },
      { atSec: 20, durationSec: 6, framing: "detail", camera: "macro", note: "Ring / contract folder" },
      { atSec: 26, durationSec: 6, framing: "wide", camera: "fade", note: "She walks past — freeze" },
    ],
    colorGrade: { contrast: 1.2, saturation: 1.05, temperature: 5, shadows: "#181820", highlights: "#f0f0ff" },
    cameraMoves: ["tracking", "slow_push", "macro"],
    musicCue: "Soft tension bed + stinger",
    accent: "#00D9FF",
    genreTags: ["indonesia", "sinetron", "asia", "rivalry", "drama"],
  },
  {
    id: "asia-jp-vlog-city",
    category: "asia",
    region: "asia",
    name: "Tokyo Morning Vlog Open",
    tagline: "Shibuya dawn — quiet walk into brand day.",
    durationSec: 22,
    aspectRatio: "9:16",
    mood: ["calm", "urban", "lifestyle"],
    lut: "Tokyo Clean",
    stylePreset: "jp_lifestyle",
    idealUse: "Creator intros, travel vlogs, lifestyle brand opens.",
    sampleScript: "VO: Day one in Tokyo. Coffee first.",
    shots: [
      { atSec: 0, durationSec: 4, framing: "wide", camera: "static", note: "Empty crosswalk dawn" },
      { atSec: 4, durationSec: 5, framing: "pov", camera: "tracking", note: "Walk through alley" },
      { atSec: 9, durationSec: 5, framing: "detail", camera: "macro", note: "Coffee pour" },
      { atSec: 14, durationSec: 4, framing: "medium", camera: "orbit", note: "Creator smile to cam" },
      { atSec: 18, durationSec: 4, framing: "logo", camera: "impact", note: "Channel title" },
    ],
    colorGrade: { contrast: 1.05, saturation: 0.95, temperature: 0, shadows: "#101018", highlights: "#ffffff" },
    cameraMoves: ["static", "tracking", "macro", "orbit", "impact"],
    musicCue: "Lo-fi Japan morning loop",
    accent: "#C4B5FD",
    genreTags: ["japan", "vlog", "tokyo", "asia", "lifestyle"],
  },

];

export function getIdealTemplate(id: string): IdealTemplate | undefined {
  return IDEAL_TEMPLATES.find((t) => t.id === id);
}

export function listIdealTemplates(category?: TemplateRoomCategory | "all"): IdealTemplate[] {
  if (!category || category === "all") return IDEAL_TEMPLATES;
  return IDEAL_TEMPLATES.filter((t) => t.category === category);
}

export function idealToTemplateJson(ideal: IdealTemplate) {
  return {
    catalogId: ideal.id,
    category: ideal.category,
    region: ideal.region,
    name: ideal.name,
    stylePreset: ideal.stylePreset,
    durationSec: ideal.durationSec,
    aspectRatio: ideal.aspectRatio,
    lut: ideal.lut,
    colorGrade: ideal.colorGrade,
    cameraMoves: ideal.cameraMoves,
    musicCue: ideal.musicCue,
    idealUse: ideal.idealUse,
    mood: ideal.mood,
    genreTags: ideal.genreTags,
    sampleScript: ideal.sampleScript,
    scenes: ideal.shots.map((s, index) => ({
      index,
      startSec: s.atSec,
      endSec: s.atSec + s.durationSec,
      cameraMove: s.camera,
      framing: s.framing,
      transition: index === 0 ? "fade" : "cut",
      note: s.note,
    })),
    characterPositions: [],
    metadata: {
      source: "templates-room",
      tagline: ideal.tagline,
      accent: ideal.accent,
    },
  };
}
